### PR TITLE
Add SwiftLint pre-commit hook and update Readme.md (#473)

### PR DESCRIPTION
**Pull request by kpavankotesh**

### CODE REVIEW

**Comment by sds** [comment]
Thanks for the pull request, @kpavankotesh!

Overall looks fine, but would really appreciate you adding tests ensuring your regex works as expected with SwiftLint's output.

Here's an example of what a test file would look like: https://github.com/jhuiting/overcommit/blob/4cf893ca3b03fb04a964777658a8aea90171d6f7/spec/overcommit/hook/pre_commit/ts_lint_spec.rb

Also, fixing other errors would also be appreciated:

```
Check for trailing whitespace....................[TrailingWhitespace] FAILED
Errors on modified lines:
/home/travis/build/brigade/overcommit/config/default.yml:581:  
...
Analyze with RuboCop........................................[RuboCop] FAILED
Errors on modified lines:
/home/travis/build/brigade/overcommit/lib/overcommit/hook/pre_commit/swift_lint.rb:13:101: C: Metrics/LineLength: Line is too long. [105/100]
```

These should be pretty easy to fix.

 Thanks!

**Comment by kpavankotesh** [comment]
Okay. I'll look into it.

**Comment by sds** [comment]
Thanks for fixing those RuboCop warnings. We'd still like to see some tests (I linked to a good example of a hook test in my earlier response) before we merge this hook.

I'm going to close this for now due to lack of movement, but feel free to reopen with the corresponding tests in place and we'll happily merge!

**Comment by sjorsvb** [comment]
Hey guys, I'm actually interested in using this. Is it ready to be merged into master?

**Comment by sds** [comment]
Only issue holding this pull request back was a set of tests, @sjorsvb.

As I mentioned above, https://github.com/jhuiting/overcommit/blob/4cf893ca3b03fb04a964777658a8aea90171d6f7/spec/overcommit/hook/pre_commit/ts_lint_spec.rb provides a clear example of what we'd like to see here.

Happy to merge once those tests are added. Thanks!

**Comment by sds** [comment]
Implemented in #603

**Pull request closed without merging**
