### PR TITLE
Add BowerInstall post-{commit,checkout,merge,rewrite} hooks

### PR DESCRIPTION
**Pull request by jawshooah**
Essentially identical to #251, but for [bower](http://bower.io/).

### CODE REVIEW

**Comment by sds** [comment]
Ignore the Appveyor failure&mdash;this is me trying to look into some Windows testing and accidentally adding this repo.

**Comment by jawshooah** [comment]
I was wondering about that. Gonna help me out with #185?

**Comment by sds** [comment]
@jawshooah was going to start poking around. My hunch is that if we modify the `PATH` variable in the integration test we'll be able to work around the issue, which I'd be ok with.

**Comment by sds** [comment]
Merged in 8c3b543.

**Pull request merged**
