### PR TITLE
Add pre-commit hook for recess

### PR DESCRIPTION
**Pull request by jawshooah**
[Recess](https://twitter.github.io/recess/) is a linter for CSS from Twitter.

### CODE REVIEW

**Comment by sds** [comment]
Not to be overly critical of what qualifies as a useful hook or not, but isn't the Recess project dead? The last commit to the repo was in 2013 and I'm not aware of any active use of it.

Happy to merge if you actually use this yourself, but I would recommend you hop on the SCSS bandwagon and use `scss-lint`. :)

**Comment by jawshooah** [comment]
I'm not using it myself, no. CSSlint development appears to have stalled over the past few months, so I was looking around for alternatives. Had never heard of Recess before, but judging from the star count, I figured some people still found it useful.

You're right, though; no reason to clutter the repo with hooks no one is using.

Regarding SCSS, I unfortunately haven't been able to convince my coworkers that switching to a preprocessor is worth the effort. Does scss-lint work with vanilla CSS?

**Comment by sds** [comment]
Yes, SCSS is a superset of CSS. This makes it ideal for teams thinking about transitioning from vanilla CSS to a preprocessor.

I mention SCSS half-jokingly since we have another project [`scss-lint`](https://github.com/brigade/scss-lint) which supports a wide array of linters. I've heard interesting things about [PostCSS](https://github.com/postcss/postcss) and while I haven't been able to try it out personally it may be an alternative worth exploring (since it too would work with vanilla CSS out of the box, allowing you to extend the standard syntax/features with plugins as you see fit).

For now, I'm going to close this PR without merging. Feel free to reopen if later on you feel this would be useful.

**Comment by lencioni** [comment]
> I've heard interesting things about PostCSS and while I haven't been able to try it out personally it may be an alternative worth exploring (since it too would work with vanilla CSS out of the box, allowing you to extend the standard syntax/features with plugins as you see fit).

I think scss-lint is the only thing that really keeps me from switching to PostCSS.

**Pull request closed without merging**
