### PR TITLE
Exclude files that don't exist from applicable_files

### LINKED ISSUE #219: "No such file or directory @ rb_sysopen" while amending to rename a file
**Problem:** Leo was amending a commit. His original commit added a file. His amend renamed that file. Overcommit was trying to run on the original file, which no longer existed (because it had been renamed).

**Solution:**
```
git stash   # stash current changes
git reset HEAD^   # reset commit he was trying to amend
rm <file that was renamed>
git add -p
git commit   # Use original commit message from gerrit, including change-id
git stash pop
git add -p
git add <new name for renamed file>
git commit --amend
```

This seems related to https://github.com/brigade/overcommit/issues/146.

### PR DESCRIPTION
**Pull request by jawshooah**
Fixes #219

### CODE REVIEW

**Comment by lencioni** [comment]
:+1: want to add a line to the changelog while you are at it?

**Comment by jawshooah** [comment]
Done!

**Comment by lencioni** [comment]
Thanks for the code @jawshooah!

**Comment by sds** [comment]
Thanks for the pull request, @jawshooah.

On deeper thought, I think I merged this too early. This doesn't solve the underlying problem, which is that `HookContext::PreCommit#modified_files` returns non-existent files. We should probably hoist a fix close to the source of the problem to properly fix this. I'm happy to look into that later.

**Comment by sds** [comment]
Closing the loop on this to say I implemented a more thorough fix with a test in b450815670a4b13b0dc94c5a7af07cd212d04fa4.

**Pull request merged**
